# Data Manipulation with PyTorch

In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
len(x), x.numel()

(12, 12)

In [4]:
x.size(), x.shape

(torch.Size([12]), torch.Size([12]))

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn((2, 3, 4))

tensor([[[-1.7974e-01,  3.4041e-01,  5.5105e-01, -3.2072e-01],
         [ 1.9060e+00,  1.0901e+00,  1.0569e+00,  1.3899e+00],
         [ 2.0415e-01, -8.3207e-01, -1.2827e-01,  1.9928e-01]],

        [[ 2.4105e-01, -5.5541e-01, -1.2528e+00,  8.9669e-01],
         [ 5.3859e-01,  1.4395e+00, -1.7235e-02,  3.4644e-02],
         [ 8.4419e-01,  6.7507e-02, -1.0416e+00,  8.7480e-04]]])

In [11]:
torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 1, 2]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2]])

## Indexing & Slicing

In [12]:
X = torch.randn((3, 4))
X

tensor([[ 1.9580,  0.6978, -1.4726,  0.8903],
        [ 0.1416, -0.1363,  0.6962,  0.3123],
        [-0.7726, -1.5115, -0.6408, -1.2030]])

In [13]:
X[0], X[1: 3], X[-1]

(tensor([ 1.9580,  0.6978, -1.4726,  0.8903]),
 tensor([[ 0.1416, -0.1363,  0.6962,  0.3123],
         [-0.7726, -1.5115, -0.6408, -1.2030]]),
 tensor([-0.7726, -1.5115, -0.6408, -1.2030]))

In [14]:
X[1:3, :2] = -0.9999
X

tensor([[ 1.9580,  0.6978, -1.4726,  0.8903],
        [-0.9999, -0.9999,  0.6962,  0.3123],
        [-0.9999, -0.9999, -0.6408, -1.2030]])

## Operations

In [15]:
torch.exp(X)

tensor([[7.0851, 2.0094, 0.2293, 2.4359],
        [0.3679, 0.3679, 2.0061, 1.3665],
        [0.3679, 0.3679, 0.5269, 0.3003]])

In [16]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.tensor([[4, 5, 6], [1, 2, 3]])

X + Y, X - Y, X * Y, X / Y, X ** Y

(tensor([[5, 7, 9],
         [5, 7, 9]]),
 tensor([[-3, -3, -3],
         [ 3,  3,  3]]),
 tensor([[ 4, 10, 18],
         [ 4, 10, 18]]),
 tensor([[0.2500, 0.4000, 0.5000],
         [4.0000, 2.5000, 2.0000]]),
 tensor([[  1,  32, 729],
         [  4,  25, 216]]))

In [17]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[1, 2, 3],
         [4, 5, 6],
         [4, 5, 6],
         [1, 2, 3]]),
 tensor([[1, 2, 3, 4, 5, 6],
         [4, 5, 6, 1, 2, 3]]))

In [18]:
X == Y

tensor([[False, False, False],
        [False, False, False]])

In [19]:
torch.sum(X), torch.sum(X, 0), torch.sum(X, 1), torch.sum(X, 0, keepdim=True), torch.sum(X, 1, keepdim=True)

(tensor(21),
 tensor([5, 7, 9]),
 tensor([ 6, 15]),
 tensor([[5, 7, 9]]),
 tensor([[ 6],
         [15]]))

## Broadcasting

In [20]:
x = torch.arange(2).reshape((1, 2))
y = torch.arange(3).reshape((3, 1))

x, y

(tensor([[0, 1]]),
 tensor([[0],
         [1],
         [2]]))

In [21]:
x + y, x * y

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2]]))

## Saving Memory

In [22]:
X, Y

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[4, 5, 6],
         [1, 2, 3]]))

In [23]:
before = id(Y)
Y = X + Y

before == id(Y)

False

In [24]:
before = id(Y)
Y[:] = X + Y

before == id(Y)

True

## Type Conversion

In [25]:
A = X.numpy()
B = torch.from_numpy(A)

X, A, B

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [26]:
B[0, 0] = 0

X, A, B

(tensor([[0, 2, 3],
         [4, 5, 6]]),
 array([[0, 2, 3],
        [4, 5, 6]]),
 tensor([[0, 2, 3],
         [4, 5, 6]]))

In [27]:
type(X), type(A), type(B)

(torch.Tensor, numpy.ndarray, torch.Tensor)

In [31]:
B[0, 0], B[0, 0].item()

(tensor(0), 0)