In [1]:
import torch

## Scalars

In [2]:
x = torch.tensor(2.0)
y = torch.tensor(3.0)

x, y

(tensor(2.), tensor(3.))

In [3]:
x + y, x * y, x ** y

(tensor(5.), tensor(6.), tensor(8.))

## Vectors

In [4]:
x = torch.arange(3, dtype=torch.float32)
y = torch.tensor([0.1, 0.2, 0.3], dtype=torch.float32)

x, y

(tensor([0., 1., 2.]), tensor([0.1000, 0.2000, 0.3000]))

In [5]:
x + y, x * y, x ** y

(tensor([0.1000, 1.2000, 2.3000]),
 tensor([0.0000, 0.2000, 0.6000]),
 tensor([0.0000, 1.0000, 1.2311]))

In [6]:
len(x), x.shape

(3, torch.Size([3]))

## Matrices

In [9]:
A = torch.arange(6).reshape(3, 2)

A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [12]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])

A, A.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]))

In [13]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## Tensors

In [16]:
torch.arange(12, dtype=torch.float32).reshape(2, 3, 2)

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]])

## Tensor Arithmetic

In [17]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()

A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [18]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [19]:
1 + A

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [20]:
A + 1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Reduction

In [24]:
torch.sum(A), torch.sum(A, axis=[0, 1])

(tensor(15.), tensor(15.))

In [25]:
torch.sum(A, axis=0), torch.sum(A, axis=1)

(tensor([3., 5., 7.]), tensor([ 3., 12.]))

In [26]:
torch.mean(A, axis=0), torch.sum(A, axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [27]:
torch.mean(A), torch.sum(A) / torch.numel(A)

(tensor(2.5000), tensor(2.5000))

## Non Reduction

In [29]:
torch.sum(A, axis=0, keepdim=True), torch.sum(A, axis=1, keepdim=True)

(tensor([[3., 5., 7.]]),
 tensor([[ 3.],
         [12.]]))

## Dot Products

In [31]:
torch.dot(x, y)

tensor(0.8000)

In [33]:
torch.sum(x * y)

tensor(0.8000)

## Matrix-Vector Multiplication

In [36]:
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [35]:
torch.mv(A, x)

tensor([ 5., 14.])

## Matrix-Matrix Multiplication

In [40]:
B = torch.ones(3, 2)
A, B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]))

In [42]:
torch.mm(A, B)

tensor([[ 3.,  3.],
        [12., 12.]])