In [1]:
import torch

In [2]:
x = torch.arange(4, dtype=torch.float32)

x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)

y = torch.dot(x, x)

y

tensor(14., grad_fn=<DotBackward0>)

In [4]:
y.backward()

x.grad

tensor([0., 2., 4., 6.])

In [7]:
x.grad == 2 * x

tensor([True, True, True, True])

In [9]:
x.grad.zero_()

y = torch.sum(x)

y.backward()
x.grad

tensor([1., 1., 1., 1.])

## Backward for Non-scalar

In [11]:
x.grad.zero_()
y = x + x

y

tensor([0., 2., 4., 6.], grad_fn=<AddBackward0>)

In [14]:
y.sum().backward()

x.grad

tensor([2., 2., 2., 2.])

## Detaching Computation

In [27]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [24]:
x.grad.zero_()

y = x * x
z = y * x

z.sum().backward()

x.grad, x.grad == 3 * x**2

(tensor([ 0.,  3., 12., 27.]), tensor([True, True, True, True]))

In [29]:
x.grad.zero_()

y = x * x
u = y.detach()
z = u * x

z.sum().backward()

x.grad, x.grad == u

(tensor([0., 1., 4., 9.]), tensor([True, True, True, True]))