# Data Manipulation with PyTorch

In [2]:
import torch

In [4]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [11]:
len(x), x.numel()

(12, 12)

In [13]:
x.size(), x.shape

(torch.Size([12]), torch.Size([12]))

In [22]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [33]:
torch.randn((2, 3, 4))

tensor([[[ 0.1312, -0.9759,  0.3505, -0.4018],
         [-0.0881, -1.1885, -0.0196, -0.7955],
         [-1.2767,  0.4578,  0.4857,  0.4180]],

        [[-0.1346,  0.1028, -0.6598, -0.2623],
         [ 1.4738,  1.1987, -0.5262, -0.9014],
         [ 0.2736, -1.3665,  0.2384, -1.2929]]])

In [35]:
torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 1, 2]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2]])

## Indexing & Slicing

In [44]:
X = torch.randn((3, 4))
X

tensor([[ 0.4597,  0.0052,  1.8734,  1.1184],
        [-0.5148, -1.2658,  0.4046,  0.3968],
        [-0.5725, -1.6315,  0.6304, -0.3921]])

In [45]:
X[0], X[1: 3], X[-1]

(tensor([0.4597, 0.0052, 1.8734, 1.1184]),
 tensor([[-0.5148, -1.2658,  0.4046,  0.3968],
         [-0.5725, -1.6315,  0.6304, -0.3921]]),
 tensor([-0.5725, -1.6315,  0.6304, -0.3921]))

In [49]:
X[1:3, :2] = -0.9999
X

tensor([[ 0.4597,  0.0052,  1.8734,  1.1184],
        [-0.9999, -0.9999,  0.4046,  0.3968],
        [-0.9999, -0.9999,  0.6304, -0.3921]])

## Operations